version: "3.1"

services:
  api:
    container_name: finance-api
    image: stivenramireza/finance-api:1.0.0
    ports:
      - 80:8000
    networks:
      - finance
    depends_on:
      - db
      - cache

  db:
    container_name: db
    image: postgres:14
    ports:
      - 5432:5432
    networks:
      - finance
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata

  cache:
    container_name: redis-cache
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - finance
    volumes:
      - cache-data:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}

networks:
  finance:

volumes:
  db-data:
    driver: local
  cache-data:
    driver: local
