version: "3.1"

services:
  api:
    container_name: api
    build: .
    ports:
      - 80:8000
    networks:
      - finance
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:14
    ports:
      - 5432:5432
    networks:
      - finance
    volumes:
      - data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata

networks:
  finance:

volumes:
  data:
