version: "3.1"

services:
  api:
    container_name: api
    build: .
    restart: always
    ports:
      - 80:8000
    networks:
      - finance
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:14
    ports:
      - 5432:5432
    networks:
      - finance
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata

networks:
  finance:

volumes:
  data:
